import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";

// docs/phase1/overlay-forge-issues.md OF-06: the entry docs drifted from the
// tree three times in one day (suite status, workflow shape, pins). These
// locks run in Verify so the drift is red in CI instead of being found by a
// reader. Nothing here changes Verify's purpose; it only reads files.

const ROOT = join(__dirname, "..", "..");
const read = (rel: string) => readFileSync(join(ROOT, rel), "utf8");

const AGENTS = read("AGENTS.md");
const BRIEF = read("docs/phase1/overlay-forge-brief.md");
const USE_FORGE = read("docs/phase1/skills/use-forge/SKILL.md");
const FORGE_YAML = read("forge.yaml");
const OVERLAY_YAML = read("overlay.yaml");
const OVERLAY_CHECK = read(".github/workflows/overlay-check.yml");

function yamlList(source: string, key: string): string[] {
  const match = source.match(new RegExp(`^${key}:\\n((?:  - .*\\n)+)`, "m"));
  assert.ok(match, `${key} list missing`);
  return match[1]
    .split("\n")
    .filter((line) => line.startsWith("  - "))
    .map((line) => line.slice(4).trim());
}

function jobNames(): Set<string> {
  const names = new Set<string>();
  for (const file of readdirSync(join(ROOT, ".github", "workflows"))) {
    const text = read(join(".github", "workflows", file));
    for (const line of text.split("\n")) {
      const job = line.match(/^    name: (.+)$/);
      if (job) names.add(job[1].trim());
    }
  }
  return names;
}

function branchRequiredChecks(branch: string): string[] {
  const block = FORGE_YAML.match(new RegExp(`^  ${branch}:\\n    required_checks:\\n((?:      - .*\\n)+)`, "m"));
  assert.ok(block, `branches.${branch}.required_checks missing`);
  return block[1].split("\n").filter((l) => l.startsWith("      - ")).map((l) => l.slice(8).trim());
}

test("forge.yaml protects dev and main and every required check is a CI job name", () => {
  assert.deepEqual(yamlList(FORGE_YAML, "protect"), ["dev", "main"]);
  const jobs = jobNames();
  for (const branch of ["dev", "main"]) {
    const required = branchRequiredChecks(branch);
    assert.ok(required.includes("overlay-check") && required.includes("forge-check"), `${branch} must require overlay-check and forge-check`);
    for (const check of required) {
      assert.ok(jobs.has(check), `${branch}: required check "${check}" is not a job name in .github/workflows (jobs: ${[...jobs].join(", ")})`);
    }
    assert.equal(required.includes("Verify"), false, "Verify is the workflow name, not a job");
  }
  assert.match(FORGE_YAML, /^    promote_from: dev$/m);
});

test("forge.yaml deny_paths cover the whole workflows directory", () => {
  const deny = yamlList(FORGE_YAML, "deny_paths");
  assert.ok(deny.includes(".github/workflows/"), "deny_paths must contain .github/workflows/");
  for (const rel of deny) {
    assert.ok(existsSync(join(ROOT, rel)), `deny_path ${rel} does not exist`);
  }
});

test("overlay-check.yml is the inline native job and the docs say so", () => {
  assert.equal(/^\s+uses: .*\/\.github\/workflows\/overlay\.yml@/m.test(OVERLAY_CHECK), false, "overlay-check.yml became a reusable caller; update AGENTS.md / brief §6 first");
  assert.match(OVERLAY_CHECK, /^    name: overlay-check$/m);
  for (const [label, text] of [["AGENTS.md", AGENTS], ["brief", BRIEF]] as const) {
    assert.equal(text.includes("reusable `uses:` + wrapper"), false, `${label} still describes the old reusable + wrapper shape`);
  }
  const ciPin = OVERLAY_CHECK.match(/ref: (overlay-v\d+\.\d+\.\d+)/);
  assert.ok(ciPin, "overlay-check.yml must pin an overlay-v* tag for the tool checkout");
  assert.ok(BRIEF.includes(ciPin[1]), `brief does not state the CI pin ${ciPin[1]}`);
  assert.ok(AGENTS.includes(ciPin[1]), `AGENTS.md does not state the CI pin ${ciPin[1]}`);
  const FORGE_CHECK = read(".github/workflows/forge-check.yml");
  const forgePin = FORGE_CHECK.match(/ref: (forge-v\d+\.\d+\.\d+)/);
  assert.ok(forgePin, "forge-check.yml must pin a forge-v* tag");
  assert.ok(BRIEF.includes(forgePin[1]) && AGENTS.includes(forgePin[1]), `docs do not state the Forge pin ${forgePin[1]}`);
  assert.match(FORGE_CHECK, /fetch-depth: 0/, "forge check needs history to diff against origin/dev");
  assert.match(FORGE_CHECK, /--check-state/);
});

test("STATE.md is generated, not hand-written, and names both protected branches", () => {
  const state = read("docs/STATE.md");
  assert.match(state, /generated by forge status; do not edit/);
  assert.match(state, /`dev`/);
  assert.match(state, /`main`/);
});

test("no hand-copied tool SHAs: pins are tags, the same in AGENTS.md, the brief and use-forge", () => {
  for (const [label, text] of [["AGENTS.md", AGENTS], ["brief", BRIEF], ["use-forge", USE_FORGE]] as const) {
    assert.equal(/(overlay|forge)-v\d+\.\d+\.\d+[^\n]*?[0-9a-f]{40}/.test(text), false, `${label} pins a SHA by hand; STATE.md and docs_sync own that`);
    assert.match(text, /overlay-v2\.\d+\.\d+/, `${label} must name the Overlay 2.x pin`);
  }
});

test("suites follow the v2 contract: active or blocked with a linked reason, no signatures", () => {
  const suites = readdirSync(join(ROOT, "suites"));
  assert.ok(suites.length > 0);
  for (const suite of suites) {
    const text = read(join("suites", suite, "suite.yaml"));
    assert.match(text, /^schema: overlay-suite\/v2$/m, `${suite}: schema must be overlay-suite/v2`);
    const status = text.match(/^status: (\w+)$/m)?.[1];
    assert.ok(status === "active" || status === "blocked", `${suite}: status ${status} is not active|blocked`);
    assert.equal(/^reviewed_by:/m.test(text), false, `${suite}: reviewed_by is gone in v2 (review = PR approval)`);
    assert.equal(/^armed_reason:/m.test(text), false, `${suite}: armed_reason is gone in v2`);
    if (status === "blocked") {
      assert.match(text, /^blocked_reason: .*(https?:\/\/|OF-\d+|#\d+|\.md)/m, `${suite}: blocked needs a linked reason`);
    }
  }
});

test("brief forbids stuffing workflow into every agent package", () => {
  assert.match(BRIEF, /按层配对/);
  assert.match(BRIEF, /不是每个 PR 都交文档 \+ 代码 \+ workflow/);
  assert.match(BRIEF, /agent 包不得改 `\.github\/workflows\/`/);
});

test("overlay.yaml default_ref is a full SHA that the brief documents", () => {
  const ref = OVERLAY_YAML.match(/^  default_ref: ([0-9a-f]{40})$/m)?.[1];
  assert.ok(ref, "overlay.yaml default_ref must be a 40-hex SHA, not a branch");
  assert.ok(BRIEF.includes(ref), `brief §6 does not mention default_ref ${ref}`);
});
